webapp/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from webapp.models import User

class RegisterForm(FlaskForm):
    first_name = StringField('First name', validators=[DataRequired(), Length(min=2, max=20)])
    last_name = StringField('Last name', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('E-mail', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email:
            raise ValidationError('The chosen email address already exists.')

class LoginForm(FlaskForm):
    email = StringField('E-mail', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')

webapp/main/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint 
from webapp import app, db ,bcrypt
from webapp.main.forms import RegisterForm, LoginForm
from webapp.models import User, Booking, Bungalow
from flask_login import login_user, current_user, logout_user, login_required

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def index():
    return render_template('home.html', css="home.css")

@main.route('/register', methods=["POST", "GET"])
def registreren():
    if current_user.is_authenticated:
        return redirect(url_for('main.account'))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data, last_name=form.last_name.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Account has been created. You can now login.", 'success')
        return redirect(url_for('main.inloggen'))

    return render_template('registreren.html', form=form, title="Register")

@main.route('/login', methods=["POST", "GET"])
def inloggen():
    if current_user.is_authenticated:
        return redirect(url_for('main.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.account'))
        else:
            flash(f"The combination of email address and password is incorrect.", 'danger')
    return render_template('login.html', form=form, title="login")

@main.route('/account')
@login_required
def account():
    bookings = Booking.query.join(Bungalow).filter(Booking.guest_id == current_user.id).all()
    return render_template('account.html', title="Account", bookings=bookings)

@main.route('/log-out')
def uitloggen():
    logout_user()
    return redirect(url_for('main.index'))

@main.errorhandler(404)
def not_found(e):
    return render_template('errors/404.html'), 404

@main.errorhandler(403)
def forbidden(e):
    return render_template('errors/403.html'), 403

app.register_error_handler(404, not_found)
app.register_error_handler(403, forbidden)

webapp/main/templates/account.html
{% extends "base.html" %}


{% block content %}
<div class="container">
  <div class="jumbotron py-5">
    <h2>Welcome {{current_user.first_name}} {{current_user.last_name}}</h2>
    <p>You can view and adjust your reservations here. Adjusting here means
      planning another week, booking another week or booking a different type of house.</p>
  </div>
  <div class="jumbotron py-3">
    <h5><u>Personal information:</u></h5>
    <p>
      <b>First name:</b> {{current_user.first_name}}
      <br>
      <b>Last name:</b> {{current_user.last_name}}
      <br>
      <b>E-mail address:</b> {{current_user.email}}
    </p>
  </div>
  {% if current_user.is_admin %}
  <a class="btn btn-primary" href="{{ url_for('bungalows.add_bungalow')}}">Add bungalow</a>
  {% endif %}
  <hr>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{category}}">
    {{message}}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}

  {% if bookings %}
  <p class="font-weight-bold">Your reservations:</p>
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Booking ID</th>
          <th scope="col">Bungalow</th>
          <th scope="col">Number of persons</th>
          <th scope="col">Week</th>
          <th scope="col">Price</th>
          <th scope="col">Options</th>
        </tr>
      </thead>
      <tbody>
        {% for booking in bookings %}
        <tr>
          <th scope="row">{{booking.id}}</th>
          <td>{{booking.bungalow.name}}</td>
          <td>{{booking.bungalow.bungalow_type}}</td>
          <td>{{booking.week}}</td>
          <td>€{{booking.bungalow.weekprice}}</td>
          <td>
            <a href="{{url_for('bookings.update_booking', booking_id=booking.id)}}"
              class="btn btn-warning">Change</a>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{booking.id}}">
              Cancel booking
            </button>

            <div class="modal fade" id="deleteModal{{booking.id}}" tabindex="-1" role="dialog"
              aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to cancel the booking?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{url_for('bookings.delete_booking', booking_id=booking.id)}}" method="post">
                      <input type="submit" class="btn btn-danger" value="Cancel booking">
                    </form>
                  </div>
                </div>
              </div>
            </div>
        </div>
        </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        {% else %}
        <div class="text-center">
          <h4>You don't have any reservations yet</h4>
        </div>
        {% endif %}
      </div>

{% endblock %}

webapp/main/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon  -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">
    <link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">


    <!-- Bootstrap  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    {% if css %}
    <link rel="stylesheet" href="/static/css/{{css}}">
    {% endif %}

    {% if title %}
    <title>{{ title }} | Bungalowpark Zee en Duin</title>
    {% else %}
    <title>Bungalowpark Zee en Duin</title>
    {% endif %}
</head>
<body>

<nav class="navbar navbar-light navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand h1" href="{{ url_for('main.index')}}">
            <img src="{{ url_for('static', filename='img/logo.png')}}" height="30" class="d-inline-block align-top" alt="">
            Bungalowpark Zee en Duin
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.index')}}">Home</a>
              </li>
              
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('bungalows.zoek')}}">Search & Book</a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.account')}}">My account</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.uitloggen')}}">Log out</a>
              </li>
              {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.inloggen')}}">Login</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.registreren')}}">Register</a>
              </li>
              {% endif %}
            </ul>
          </div>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

webapp/main/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron py-3">
    <div class="container">
    <h1>Bungalowpark Zee en Duin</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel nibh at purus ultrices sollicitudin et et leo. Etiam pellentesque nibh at lacus porta, non commodo nulla bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed a cursus arcu. Donec fringilla tempor suscipit. Maecenas tristique convallis dolor, vitae facilisis ipsum eleifend eget. Morbi consectetur porttitor ipsum, eget rutrum orci dignissim in. Nullam ut neque facilisis, commodo purus sed, pretium leo.
        
        Cras posuere, dui quis pellentesque vehicula, elit sapien interdum augue, ut tristique sapien ex sed nunc. Aliquam eget metus et arcu porta sollicitudin. Vestibulum.</p>
    </div>
</div>
{% endblock %}

webapp/main/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form class="text-center mt-5" action="" method="post">
            <h1 class="h2 mb-4 font-weight-normal">login</h1>
                <div class="row justify-content-center">
                    <div class="form-group col-md-7">

                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                            <div class="alert alert-{{category}}">
                                {{message}}
                            </div>
                            {% endfor%}
                        {% endif%}
                        {% endwith %}

                        {{ form.hidden_tag() }}
                        
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg", autocomplete="off") }}
                    {% endif %}
                    </div>
                </div>   
            <div class="row justify-content-center">
                <div class="form-group col-md-7 px-4">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid", autocomplete="off") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg", autocomplete="off") }}
                {% endif %}
                </div>
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label mb-3")}}
            </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <div class="pt-3">
            <small class="text-muted">
                Don't have an account yet?<a class="ml-2" href="{{ url_for('main.registreren')}}">Register</a>
            </small>
        </div>
    </form>
</div>
{% endblock %}

webapp/main/templates/registreren.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form class="text-center mt-5" action="" method="post">
                <h1 class="h2 mb-4 font-weight-normal">Register</h1>
                    <div class="row justify-content-center">
                        <div class="form-group col-md-7 px-4">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                            <div class="alert alert-{{category}}">
                                {{message}}
                            </div>
                            {% endfor%}
                        {% endif%}
                        {% endwith %}

                        {{ form.hidden_tag() }}
                        
                        {{ form.first_name.label(class="form-control-label") }}
                        {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                            {{ form.first_name(class="form-control form-control-lg") }}
                        {% endif %}
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <div class="form-group col-md-7 px-4">
                            {{ form.last_name.label(class="form-control-label") }}
                            {% if form.last_name.errors %}
                            {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.last_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.last_name(class="form-control form-control-lg") }}
                        {% endif %}
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <div class="form-group col-md-7 px-4">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="form-group col-md-7 px-4">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="form-group col-md-7 px-4">
                            {{ form.confirm_password.label(class="form-control-label") }}
                            {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                    <div class="py-3">
                    <small class="text-muted">
                        Do you already have an account?<a class="ml-2" href="{{ url_for('main.inloggen')}}">login</a>
                    </small>
                </div>
            </form>
    </div>
  
{% endblock %}